services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-tracking-server
    ports:
      - "5555:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /tmp/mlruns
      --allowed-hosts '*'
      --cors-allowed-origins '*'
